# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'GomiClient' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for GomiClient

  # Required by RNFirebase
  # pod 'GoogleAppMeasurement', '~> 5.2.0'
  pod 'Firebase/Core', '~> 5.11.0'
  pod 'Firebase/Messaging', '~> 5.11.0'

  target 'GomiClientTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'GomiClient-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for GomiClient-tvOS

  target 'GomiClient-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
